# Site settings
title: Archipelago Fishing
header-img: 'img/old_cinema.jpg'
email: info@example.com
description: "Archipelago Fishing"
baseurl: "/archipelagofishing.com"
url: "http://jacobburenstam.com"
facebook_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
